apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-deployment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/xellsys/argo-app.git
    targetRevision: HEAD
    path: crossplane/deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
